name: Compile UDF

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-udf:
    runs-on: ubuntu-latest
    container: precice/precice:nightly

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: apt-get update && apt-get install -y build-essential

      - name: Set PRECICE_PATH environment variable
        run: echo "PRECICE_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Copy needed files
        run: |
          rm -rf examples/Cavity2D/libudf
          set -e
          mkdir examples/Cavity2D/libudf examples/Cavity2D/libudf/lnamd64 examples/Cavity2D/libudf/lnamd64/2ddp_host
          cp -r tests/makefile examples/Cavity2D/libudf/lnamd64/2ddp_host
          cp src/fsi.c src/fsi.h src/fsi_udf.c src/user.udf examples/Cavity2D/libudf/lnamd64/2ddp_host
          mkdir examples/Cavity2D/libudf/lnamd64/2ddp_host/mocked_folders
          cp -r tests/mocks/* examples/Cavity2D/libudf/lnamd64/2ddp_host/mocked_folders

      - name: Compile the UDF
        working-directory: examples/Cavity2D/libudf/lnamd64/2ddp_host
        run: make
