name: Compile UDF

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-udf:
    runs-on: ubuntu-latest
    container: precice/precice:nightly

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: apt-get update && sudo apt-get install -y build-essential

      - name: Compile the UDF
        working-directory: examples/Cavity2D/libudf/lnamd64/2ddp_host
        run: make
